# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, verbose_name='Identificador')),
                ('level_inicial', models.IntegerField(verbose_name='Level Inicial')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('evolucao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.Pokemons')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo.Tipo')),
            ],
            options={
                'ordering': ['nome'],
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Pokemons',
            },
        ),
    ]
